### ISSUE TITLE
LSP for this project

### ISSUE THREAD

**Issue by juleiste** [SuperOffice/vscode-crmscript#24]
Hello, 

I've experimented with an Language Server Provider (LSP) for CRMscript written in Typescript. 
I have my own extension for vscode that uses this LSP to support completion and Hover(for now). 
It also downloads the reference-library from docs (the .yml-files) so it should stay up2date as long as the docs are updated. The .yml-files are used to supply CompletionItems. 

Its kind of a big change to use an LSP, so I thought it was a good idea to ask before I possibly create a pull-request for it. 
I also have various different suggestions for how this project is structured, but I'm unsure how many others are still invested into this (?)

//Eivind

**Comment by SuperOfficeDevNet** [comment]
Hi Eivind! This is a very welcome activity on this project. 💯 We would very much like to see improvements here, and this is one that is very very interesting!

**Comment by juleiste** [comment]
Created a pull-request for it now. It's still very much a work in progress, but the CompletionItems are already a little bit ahead of what was present in this project. All the other functionality is un-touched, I only added the LSP and commented out the old intellisense.
