### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by sw3Dan** [SuperOffice/vscode-crmscript#36]
Using the id and secret located in my custom pre-stage SOD application, I am first greated with a error when signing in and afterwards a success when pressing 'Try again'.. but there is no success in fetching a token to the vscode plugin.

I can not find a general guide if there is some kind of requirements of the id/secret supplied..-

------------------------------
Approve application
'Error occured
We are currently experiencing some technical difficulties.
Request ID: 00-5a630675fed518b1aa61a793cde16dee-5019d642622103d9-00

Click here to go to the support centre.
Try Again
------------------------------

[Try again]  successfully loges me in

------------------------------

Visual Studio Code

Command 'Cirrus: Download scripts to the current folder' resulted in an error

Cannot read properties of undefined (reading 'accessToken')

**Comment by MargretheR** [comment]
Hi Dan, add the redirect URL to the allowed list on the apps configuration:
https://docs.superoffice.com/en/developer-portal/create-app/config/cors-and-redirection-urls.html
You'll probably need me to add access to the CRMScript agent, send us an email to appdev@superoffice.com - include a link to the app configuration you're using.
