### ISSUE TITLE
"Authorization error: InvalidRedirectUrl (2)" error when using "Cirrus: Login" command

### ISSUE THREAD

**Issue by Scalpel78** [SuperOffice/vscode-crmscript#5]
Hi, just tried using one of my existing test-applications in SOD. After logging in I end up here:

![image](https://user-images.githubusercontent.com/1316578/47166791-3f93a680-d2fd-11e8-9412-7458cb25f0f5.png)

Most likely the app hasn't been defined properly in SOD (which is understandable because I just reused one I had). The ReadMe.md should probably contain some information about what requirements there are for the SOD-App. Maybe the app shouldn't have a redirect login at all...?

**Comment by Scalpel78** [comment]
Solved by setting up http://localhost:4300 as an allowed redirectUrl on the app.

**Comment by MargretheR** [comment]
Which means you'll need us to whitelist the redirect urls on the app, just email appdev@superoffice.com
