### ISSUE TITLE
Custom code-snippets not working

### ISSUE THREAD

**Issue by giddorah** [SuperOffice/vscode-crmscript#6]
If we add custom snippets to the crmscript.json-file they are only available for the first couple of seconds of a Visual Studio Code-restart. Then it seems that something makes the VSCode Language Service turns off.

After load:
![image](https://user-images.githubusercontent.com/20879348/47418493-7f81e000-d77a-11e8-8ba0-4dd6acd45958.png)

After a couple of seconds:
![image](https://user-images.githubusercontent.com/20879348/47418527-8f012900-d77a-11e8-92d5-d60919d5207e.png)

It would be awesome if this could be fixed.

**Comment by Scalpel78** [comment]
This should be fixed now.
