### ISSUE TITLE
meta.json created, but no scriptfiles: GetCRMScriptByUniqueIdentifier not allowed

### ISSUE THREAD

**Issue by Scalpel78** [SuperOffice/vscode-crmscript#7]
When running the "Download scripts to current folder" command I get a big meta.json file, which correctly lists data about the scripts in my SOD database, but no scriptfiles are created.

After putting in a console.error in getScriptSource() in api.ts I get this error printed out:

{
  "Error": true,
  "ErrorType": "UnauthorizedAccessException",
  "Message": "Client has not been granted access rights to web service CRMScript.GetCRMScriptByUniqueIdentifier: Application is not authorized - Denied",
  "ErrorSource": "SuperOffice.Online.ConfigOverride"
}

So the application can get the meta-data about the scripts, but not the actual sourcecode?  Do I need more rights on my app?

**Comment by MargretheR** [comment]
You do, this is a protected agent and I need to set it up on the app. Will extend the app registration form to include this.

**Comment by Scalpel78** [comment]
Thanks, after you enabled it on my app the sourcecode is successfully downloaded.
![image](https://user-images.githubusercontent.com/1316578/47563023-c3164e80-d920-11e8-8718-8a6cde9d87e9.png)
