### ISSUE TITLE
Error in Login method

### ISSUE THREAD

**Issue by juleiste** [SuperOffice/vscode-crmscript#9]
When using the Cirrus: Login-method , after signing into SuperOffice, you get a 400 error on the callback: 
![image](https://user-images.githubusercontent.com/60758190/74748457-d4e3d980-5268-11ea-9010-b6aee2c6eb29.png)

**Comment by josteink** [comment]
Hey @juleiste!

Errors are hard without enough logging, and I don't think the log provided is enough to solve this issue.

If you could attach a screenshot of the network inspector and the response to the request causing the 400 error, that would be very helpful, and might help us/you determine why authentication is failing.
